# Generated by Django 3.2.7 on 2021-09-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='substitutes_saved',
        ),
    ]
